services:
  sandbox:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    restart: "no"
    volumes:
      - ./target:/target
      - ./.claude:/home/basic/.claude
      - ./.claude.json:/home/basic/.claude.json
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1024M
        reservations:
          memory: 256M
